//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyHospital
{
    using System;
    using System.Collections.Generic;
    
    public partial class Colonias
    {
        public Colonias()
        {
            this.Direccion = new HashSet<Direccion>();
        }
    
        public int nIdColonia { get; set; }
        public string sColonia { get; set; }
        public string sCP { get; set; }
        public int nIdMunicipio { get; set; }
    
        public virtual Municipios Municipios { get; set; }
        public virtual ICollection<Direccion> Direccion { get; set; }
    }
}
