//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyHospital
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estados
    {
        public Estados()
        {
            this.Cuidades = new HashSet<Cuidades>();
        }
    
        public int nIdEstado { get; set; }
        public string sEstado { get; set; }
        public int nIdPais { get; set; }
    
        public virtual ICollection<Cuidades> Cuidades { get; set; }
        public virtual Paises Paises { get; set; }
    }
}
