//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyHospital
{
    using System;
    using System.Collections.Generic;
    
    public partial class GposSanguineos
    {
        public GposSanguineos()
        {
            this.Pacientes = new HashSet<Pacientes>();
        }
    
        public int nIdGpoSanguineo { get; set; }
        public string sDescripcion { get; set; }
        public bool bActivo { get; set; }
    
        public virtual ICollection<Pacientes> Pacientes { get; set; }
    }
}
