//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyHospital
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roles
    {
        public Roles()
        {
            this.USUARIOS = new HashSet<USUARIOS>();
        }
    
        public int nIdRol { get; set; }
        public string sDescripcion { get; set; }
        public bool bActivo { get; set; }
    
        public virtual ICollection<USUARIOS> USUARIOS { get; set; }
    }
}
