//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyHospital.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dbHospitalEntities : DbContext
    {
        public dbHospitalEntities()
            : base("name=dbHospitalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Agenda> Agenda { get; set; }
        public DbSet<CamposHistClin> CamposHistClin { get; set; }
        public DbSet<Colonias> Colonias { get; set; }
        public DbSet<Consulta> Consulta { get; set; }
        public DbSet<Cuidades> Cuidades { get; set; }
        public DbSet<Direccion> Direccion { get; set; }
        public DbSet<Estados> Estados { get; set; }
        public DbSet<GposSanguineos> GposSanguineos { get; set; }
        public DbSet<HitorialClinico> HitorialClinico { get; set; }
        public DbSet<Hospitales> Hospitales { get; set; }
        public DbSet<Medicamentos> Medicamentos { get; set; }
        public DbSet<Municipios> Municipios { get; set; }
        public DbSet<Pacientes> Pacientes { get; set; }
        public DbSet<Paises> Paises { get; set; }
        public DbSet<Recetas> Recetas { get; set; }
        public DbSet<Roles> Roles { get; set; }
        public DbSet<USUARIOS> USUARIOS { get; set; }
        public DbSet<medicamentosrecetas1> medicamentosrecetas1Conjunto { get; set; }
        public DbSet<Medico> Medico { get; set; }
    
        public virtual ObjectResult<SP_GET_RECETA_Result> SP_GET_RECETA(Nullable<int> nIdConsulta)
        {
            var nIdConsultaParameter = nIdConsulta.HasValue ?
                new ObjectParameter("nIdConsulta", nIdConsulta) :
                new ObjectParameter("nIdConsulta", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_RECETA_Result>("SP_GET_RECETA", nIdConsultaParameter);
        }
    
        public virtual ObjectResult<SP_GET_RECETA1_Result> SP_GET_RECETA1(Nullable<int> nIdConsulta)
        {
            var nIdConsultaParameter = nIdConsulta.HasValue ?
                new ObjectParameter("nIdConsulta", nIdConsulta) :
                new ObjectParameter("nIdConsulta", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_RECETA1_Result>("SP_GET_RECETA1", nIdConsultaParameter);
        }
    }
}
