//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyHospital.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Colonias
    {
        public int nIdColonia { get; set; }
        public string sColonia { get; set; }
        public string sCP { get; set; }
        public int nIdMunicipio { get; set; }
        public Nullable<int> nIdCiudad { get; set; }
    }
}
