//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyHospital.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuidades
    {
        public Cuidades()
        {
            this.Municipios = new HashSet<Municipios>();
        }
    
        public int nIdCuidad { get; set; }
        public string sCuidad { get; set; }
        public int nIdEstado { get; set; }
    
        public virtual Estados Estados { get; set; }
        public virtual ICollection<Municipios> Municipios { get; set; }
    }
}
