//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyHospital.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hospitales
    {
        public int nIdHospital { get; set; }
        public string sNombre { get; set; }
        public string sLogo { get; set; }
        public string sTel1 { get; set; }
        public string sTel2 { get; set; }
        public string sEmail { get; set; }
        public int nIdDireccion { get; set; }
        public bool bActivo { get; set; }
    }
}
