//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyHospital.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medico
    {
        public int nIdMedico { get; set; }
        public string sSexo { get; set; }
        public string sEspecialidad { get; set; }
        public string sCedulaProf { get; set; }
        public int nIdUsuario { get; set; }
    
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
