//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyHospital.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicamentosRecetas
    {
        public int nIdReceta { get; set; }
        public int nUnidades { get; set; }
        public string sObservaciones { get; set; }
        public string sNombre { get; set; }
    }
}
