//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyHospital.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paises
    {
        public Paises()
        {
            this.Estados = new HashSet<Estados>();
        }
    
        public int nIdPais { get; set; }
        public string sPais { get; set; }
    
        public virtual ICollection<Estados> Estados { get; set; }
    }
}
