//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyHospital.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recetas
    {
        public int nIdreceta { get; set; }
        public int nIdMedicamento { get; set; }
        public string sObservaciones { get; set; }
        public bool bActivo { get; set; }
        public int nIdConsulta { get; set; }
    
        public virtual Consulta Consulta { get; set; }
        public virtual Medicamentos Medicamentos { get; set; }
    }
}
