//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyHospital.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOS
    {
        public USUARIOS()
        {
            this.Medicamentos = new HashSet<Medicamentos>();
        }
    
        public int nIdUsuario { get; set; }
        public string sNombre { get; set; }
        public string sPrimerApellido { get; set; }
        public string sSegundoApellido { get; set; }
        public int nIdRol { get; set; }
        public string sImagen { get; set; }
        public string sUsuario { get; set; }
        public string sContraseña { get; set; }
        public int nIdHospital { get; set; }
        public bool bActivo { get; set; }
        public Nullable<int> nIdDireccion { get; set; }
    
        public virtual ICollection<Medicamentos> Medicamentos { get; set; }
    }
}
